#create a workflow to deploy the features directory

name: Deploy Features

on:
  push:
    branches: [ main ]
    paths:
      - 'features/**'
      - '.github/workflows/deploy-features.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: ${{ github.repository_owner }}/devcontainers

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          disable-repo-tagging: "true"
          base-path-to-features: "./features"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}